PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_reset_tokens_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2023_04_06_072744_create_mailer_lite_api_keys_table',1);
INSERT INTO migrations VALUES(6,'2023_04_10_120903_create_subscribers_table',1);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "mailer_lite_api_keys" ("id" integer primary key autoincrement not null, "api_key" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO mailer_lite_api_keys VALUES(1,'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiI0IiwianRpIjoiYjg1YTgzMTMwMmEwYTE0NmZmYTE4Y2I0NWJhYWM2MDNjMmU2YzgxODY2NWFiNjc4MmVhNmJlYjUyMjU0NzhlYmU0ZTg3NjA4NjNiYjkwNDIiLCJpYXQiOjE2ODA3NjM4MzEuNTE3NjMxLCJuYmYiOjE2ODA3NjM4MzEuNTE3NjM0LCJleHAiOjQ4MzY0Mzc0MzEuNDgxNjU2LCJzdWIiOiI0MjEyOTUiLCJzY29wZXMiOltdfQ.Yo_pAu9N8njK319WQEz4o7TrxAXNQy6PJlyL3lp7T0Kpd3BcaBhWuWRPfLVxXNovGJ4I5-IDumbXLiz0BOaLLkp21ZERvL10bZqc9tQrVXxI9dMrkcqnmVobnszNy3hf8HlCmguYk7gaU5SVPagXnUXadygb1TOWk-vr6rm_GL-Gxs0umKXRkHsUNPgmvWrflDdFq_dahQ4rWsdP2lAkX8lVHOrVISZBUjYtxMB6u0FN-c2rWTtlRvNtg_PCwbQ7FrVzPloIdoKYHFEEk-LIXLHZAW7RgPJU2FVq7K0z3I6Rm40OUzhfvJFSZW_Ax19n1AaXwkJm3Dm2DBTnr7Izp1Ml00Mzhr4j7cvVscmkEt3SnJOC31Zecdf_HPqFQGEah4ErpTaIxPcKBghc6QdnIeR4_Rbv_OS7f03ixTF2fhpdxbKCXGrvSYqj8lC5Y7cRnV3hUYMFDM94gF0rWmmbkLG3rexMwxLbq3nNqRQ0H60fcYEdFWiO8q8qV_I_9KQbANnJFYAZxo8LGLszjYYmVT6XnhDf-1R9cFOhg5QiW8MQikrnByZ_85_nYZtBXeE-rT083tkayZqcUlBZF803CDewVchJPKtilYlH-rJisNkz_M4dJnJP813flEHx4Z3rKK3BDYVJIXnnR9qf6MMLviEFJLxYu9BcMgd99K1_mOU','2023-04-11 22:34:25','2023-04-11 22:34:25');
CREATE TABLE IF NOT EXISTS "subscribers" ("id" integer primary key autoincrement not null, "email" varchar not null, "name" varchar, "country" varchar, "created_at" datetime, "updated_at" datetime);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('migrations',6);
INSERT INTO sqlite_sequence VALUES('mailer_lite_api_keys',1);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE UNIQUE INDEX "mailer_lite_api_keys_api_key_unique" on "mailer_lite_api_keys" ("api_key");
CREATE UNIQUE INDEX "subscribers_email_unique" on "subscribers" ("email");
COMMIT;
